### ISSUE TITLE
On the gamma-ray emission from the core of the Sagittarius dwarf galaxy

### ISSUE THREAD

**Issue by micheledoro** [micheledoro/gDMbounds#1]
I am talking about this: 

On the gamma-ray emission from the core of the Sagittarius dwarf galaxy 
Addy J Evans, Louis E Strigari, Oskar Svenborn, Andrea Albert, J Patrick Harding, Dan Hooper, Tim Linden, Andrew B Pace
Monthly Notices of the Royal Astronomical Society, Volume 524, Issue 3, September 2023, Pages 4574–4585, https://doi.org/10.1093/mnras/stad2074
Published: 13 July 2023

https://academic.oup.com/mnras/article/524/3/4574/7223993

This paper describes M53/Sagittarius with Fermi as possible hints of DM at about 8-30 GeV.

<img width="578" alt="image" src="https://github.com/micheledoro/gDMbounds/assets/3390067/510fd991-741a-404d-8e54-f613dc8f6536">
In principle we could add 'fig7' to gDMbounds. It would be the first time we add a coutour plot and not an upper/lower limit. We should discuss how to do that. Possibly out of reach for @andreasantarossa thesis timeline, but not said already.

**Comment by micheledoro** [comment]
[stad2074.pdf](https://github.com/micheledoro/gDMbounds/files/13444341/stad2074.pdf)

**Comment by andreasantarossa** [comment]
Added dmbound file here: https://github.com/micheledoro/gDMbounds/tree/main/dmbounds/bounds/lat
