### ISSUE TITLE
Prospects for γ-ray observations of the Perseus galaxy cluster with the Cherenkov Telescope Array

### ISSUE THREAD

**Issue by micheledoro** [micheledoro/gDMbounds#17]
CTA coll: https://arxiv.org/abs/2309.03712 (to be published)

<img width="770" alt="image" src="https://github.com/micheledoro/gDMbounds/assets/3390067/4fa98104-a0c0-42d5-a3a0-4940ee81d810">

<img width="772" alt="image" src="https://github.com/micheledoro/gDMbounds/assets/3390067/faf496df-5e05-4ba4-bd5f-99d620989496">

<img width="777" alt="image" src="https://github.com/micheledoro/gDMbounds/assets/3390067/3c9fbdb1-019b-4d7f-b47b-be2fcbce35d4">

**Comment by andreasantarossa** [comment]
Limits added here: https://github.com/micheledoro/gDMbounds/tree/santarossa/dmbounds/bounds/cta
