### ISSUE TITLE
Sensitivity of the Cherenkov Telescope Array to dark subhalos

### ISSUE THREAD

**Issue by micheledoro** [micheledoro/gDMbounds#18]
[Sensitivity of the Cherenkov Telescope Array to dark subhalos](https://inspirehep.net/literature/1842713)
#1
[Javier Coronado-Blázquez](https://inspirehep.net/authors/1744373)([Madrid, Autonoma U.](https://inspirehep.net/institutions/902976)), [Michele Doro](https://inspirehep.net/authors/1026760)([INFN, Padua](https://inspirehep.net/institutions/902884)), [Miguel A. Sánchez-Conde](https://inspirehep.net/authors/1038271)([Madrid, Autonoma U.](https://inspirehep.net/institutions/902976)), [Alejandra Aguirre-Santaella](https://inspirehep.net/authors/1930829)([Madrid, Autonoma U.](https://inspirehep.net/institutions/902976)) (Jan 25, 2021)
Published in: Phys.Dark Univ. 32 (2021) 100845 • e-Print: [2101.10003](https://arxiv.org/abs/2101.10003) [astro-ph.HE]

https://www.sciencedirect.com/science/article/pii/S2212686421000753?via%3Dihub

<img width="363" alt="image" src="https://github.com/micheledoro/gDMbounds/assets/3390067/5f473a76-17de-4ad8-90e0-1d965efd8bfe">

**Comment by andreasantarossa** [comment]
Added heare: https://github.com/micheledoro/gDMbounds/tree/santarossa/dmbounds/bounds/cta
