### ISSUE TITLE
Legacy Analysis of Dark Matter Annihilation from the Milky Way Dwarf Spheroidal Galaxies with 14 Years of Fermi-LAT Data

### ISSUE THREAD

**Issue by micheledoro** [micheledoro/gDMbounds#3]
https://arxiv.org/abs/2311.04982 (Legacy Analysis of Dark Matter Annihilation from the Milky Way Dwarf Spheroidal Galaxies with 14 Years of Fermi-LAT Data)

This paper from Fermi-LAT members reports a detailed analysis on _all_ dSphs observable from Fermi-LAT, in some cases assuming their J-factors. 

Figure 6 reports the limits. Black solid lines to be extrapolated.
![image](https://github.com/micheledoro/gDMbounds/assets/3390067/579e6836-f2f2-4697-b772-52c5a8ab5308)

**Comment by andreasantarossa** [comment]
Added dmbounds file for "Legacy Analysis of Dark Matter Annihilation from the Milky Way Dwarf Spheroidal Galaxies with 14 Years of Fermi-LAT Data" paper.

**Comment by micheledoro** [comment]
Hi @andreasantarossa I think you did not merge it into the main branch of this repository. At least I cannot find it.

**Comment by andreasantarossa** [comment]
Hi @micheledoro They are on my branch, now I marge it into the main.

**Comment by micheledoro** [comment]
Limits added here: https://github.com/micheledoro/gDMbounds/tree/main/dmbounds/bounds/lat
