### ISSUE TITLE
Constraints on heavy decaying dark matter from 570 days of LHAASO observations

### ISSUE THREAD

**Issue by micheledoro** [micheledoro/gDMbounds#5]
## Paper details
LHAASO Collaboration, S.Ando, M.Chianese, D.F.G.Fiorillo, G.Miele, K.C.Y.Ng 	
https://doi.org/10.48550/arXiv.2210.15989
https://doi.org/10.1103/PhysRevLett.129.261103

## Interesting Figures
Just fig 1 with limits on decaying DM

<img width="923" alt="image" src="https://github.com/micheledoro/gDMbounds/assets/3390067/a58c55c2-7613-4a17-9c09-86480c59e2b8">

**Comment by andreasantarossa** [comment]
Limits added here: https://github.com/micheledoro/gDMbounds/tree/main/dmbounds/bounds/lhaaso

**Comment by andreasantarossa** [comment]
Limits added here: https://github.com/micheledoro/gDMbounds/tree/main/dmbounds/bounds/lhaaso
